JADWAL_IMG_DIR = "image/jadwal_bg/"
USER_IMG_DIR ="image/user_img/"
PENDETA_IMG_DIR= "image/pendeta_img/"
GEREJA_IMG_DIR= "image/gereja_img/"
KESAKSIAN_IMG_DIR="image/kesaksian_bg/"
ACARA_IMG_DIR="image/acara_bg/"
FEEDBACK_IMG_DIR="image/feedback_bg/"